name: runtestsFUSE
on:
  workflow_dispatch:
jobs:
  triggerruntest:
    runs-on: ubuntu-latest
    steps:
      - name: trigger runtest fuse
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PTP_READ_TOKEN }} # Fine-grained GitHub PAT that was saved as repository secret
          script: |
              await github.rest.actions.createWorkflowDispatch({
              owner: 'ProjectTorreyPines',
              repo: 'FUSE.jl',
              workflow_id: runtests,
              ref: 'master'
              })